In [ ]:
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, LSTM, GRU, SimpleRNN, Conv1D, TimeDistributed, MaxPooling1D, Flatten, Dropout
from tensorflow.keras import optimizers
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/ecom-user-churn-data.csv", index_col="visitorid")

In [ ]:
df.head()

,ses_rec,ses_rec_avg,ses_rec_sd,ses_rec_cv,user_rec,ses_n,ses_n_r,int_n,int_n_r,tran_n,...,int_cat16_n,int_cat17_n,int_cat18_n,int_cat19_n,int_cat20_n,int_cat21_n,int_cat22_n,int_cat23_n,int_cat24_n,target_class
visitorid,,,,,,,,,,,,,,,,,,,,,
89,23.0,16.0,0.0,0.0,39.0,2.0,0.051282,3.0,1.500000,0.0,...,0,0,0,0,3,0,0,0,0,1
251,23.0,61.0,0.0,0.0,85.0,2.0,0.023529,2.0,1.000000,0.0,...,0,0,0,0,0,0,1,0,0,1
270,14.0,0.1,0.3,3.0,21.0,11.0,0.523810,13.0,1.181818,0.0,...,0,0,0,0,0,0,13,0,0,1
298,11.0,13.0,0.0,0.0,24.0,2.0,0.083333,4.0,2.000000,0.0,...,0,0,0,3,1,0,0,0,0,1
474,16.0,26.0,0.0,0.0,43.0,2.0,0.046512,2.0,1.000000,0.0,...,2,0,0,0,0,0,0,0,0,1

In [ ]:
df.columns

Index(['ses_rec', 'ses_rec_avg', 'ses_rec_sd', 'ses_rec_cv', 'user_rec',
       'ses_n', 'ses_n_r', 'int_n', 'int_n_r', 'tran_n', 'tran_n_r', 'rev_sum',
       'rev_sum_r', 'major_spend_r', 'int_cat_n_avg', 'int_itm_n_avg',
       'ses_mo_avg', 'ses_mo_sd', 'ses_ho_avg', 'ses_ho_sd', 'ses_wknd_r',
       'ses_len_avg', 'time_to_int', 'time_to_tran', 'int_cat1_n',
       'int_cat2_n', 'int_cat3_n', 'int_cat4_n', 'int_cat5_n', 'int_cat6_n',
       'int_cat7_n', 'int_cat8_n', 'int_cat9_n', 'int_cat10_n', 'int_cat11_n',
       'int_cat12_n', 'int_cat13_n', 'int_cat15_n', 'int_cat16_n',
       'int_cat17_n', 'int_cat18_n', 'int_cat19_n', 'int_cat20_n',
       'int_cat21_n', 'int_cat22_n', 'int_cat23_n', 'int_cat24_n',
       'target_class'],
      dtype='object')

In [ ]:
from sklearn import preprocessing

cols = ['ses_rec', 'ses_rec_avg', 'ses_rec_sd', 'ses_rec_cv', 'user_rec',
       'ses_n', 'ses_n_r', 'int_n', 'int_n_r', 'tran_n', 'tran_n_r', 'rev_sum',
       'rev_sum_r', 'major_spend_r', 'int_cat_n_avg', 'int_itm_n_avg',
       'ses_mo_avg', 'ses_mo_sd', 'ses_ho_avg', 'ses_ho_sd', 'ses_wknd_r',
       'ses_len_avg', 'time_to_int', 'time_to_tran', 'int_cat1_n',
       'int_cat2_n', 'int_cat3_n', 'int_cat4_n', 'int_cat5_n', 'int_cat6_n',
       'int_cat7_n', 'int_cat8_n', 'int_cat9_n', 'int_cat10_n', 'int_cat11_n',
       'int_cat12_n', 'int_cat13_n', 'int_cat15_n', 'int_cat16_n',
       'int_cat17_n', 'int_cat18_n', 'int_cat19_n', 'int_cat20_n',
       'int_cat21_n', 'int_cat22_n', 'int_cat23_n', 'int_cat24_n']


min_max_scaler = preprocessing.MinMaxScaler()
df[cols] = min_max_scaler.fit_transform(df[cols])

In [ ]:
df.head()

,ses_rec,ses_rec_avg,ses_rec_sd,ses_rec_cv,user_rec,ses_n,ses_n_r,int_n,int_n_r,tran_n,...,int_cat16_n,int_cat17_n,int_cat18_n,int_cat19_n,int_cat20_n,int_cat21_n,int_cat22_n,int_cat23_n,int_cat24_n,target_class
visitorid,,,,,,,,,,,,,,,,,,,,,
89,0.741935,0.161616,0.000000,0.079840,0.393939,0.000000,0.055331,0.000180,0.008621,0.0,...,0.000000,0.0,0.0,0.000000,0.009464,0.0,0.000000,0.0,0.0,1
251,0.741935,0.616162,0.000000,0.079840,0.858586,0.000000,0.053870,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000438,0.0,0.0,1
270,0.451613,0.001010,0.006316,0.319358,0.212121,0.019027,0.080201,0.001983,0.003135,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.005697,0.0,0.0,1
298,0.354839,0.131313,0.000000,0.079840,0.242424,0.000000,0.057018,0.000361,0.017241,0.0,...,0.000000,0.0,0.0,0.005319,0.003155,0.0,0.000000,0.0,0.0,1
474,0.516129,0.262626,0.000000,0.079840,0.434343,0.000000,0.055080,0.000000,0.000000,0.0,...,0.003472,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,1

In [ ]:
df.shape

(49358, 48)

In [ ]:
thresh = int(len(df) * .8)

train_x, train_y = df[cols].iloc[:thresh].to_numpy(), df["target_class"].iloc[:thresh].to_numpy()


val_x, val_y = df[cols].iloc[thresh:].to_numpy(), df["target_class"].iloc[thresh:].to_numpy()

In [ ]:
train_x = train_x.reshape((-1, 47, 1))

val_x = val_x.reshape((-1, 47, 1))

In [ ]:
def init_model():
    model = Sequential()
    model.add(Conv1D(filters=8, kernel_size=2, activation='relu', padding='same', input_shape=(47, 1)))

    model.add(MaxPooling1D(pool_size=2))
    model.add(LSTM(16))
    model.add(Flatten())
    model.add(Dense(1, activation='softmax'))

    adam = optimizers.Adam(learning_rate=0.001)

    model.compile(optimizer=adam,
                  loss='binary_crossentropy',
                  metrics=[tf.keras.metrics.Precision()])
    return model

model = init_model()

model.summary()

Model: "sequential_28"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv1d_26 (Conv1D)          (None, 47, 8)             24

 max_pooling1d_23 (MaxPooli  (None, 23, 8)             0
 ng1D)

 lstm_23 (LSTM)              (None, 16)                1600

 flatten_25 (Flatten)        (None, 16)                0

 dense_24 (Dense)            (None, 1)                 17

=================================================================
Total params: 1641 (6.41 KB)
Trainable params: 1641 (6.41 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
history = model.fit(train_x, train_y, epochs = 5, validation_data = (val_x, val_y),
                    batch_size = 512)

Epoch 1/5
78/78 [==============================] - 2s 30ms/step - loss: 1.9333 - precision_16: 0.8847 - recall_15: 1.0000 - val_loss: 1.8623 - val_precision_16: 0.8890 - val_recall_15: 1.0000
Epoch 2/5
78/78 [==============================] - 3s 44ms/step - loss: 1.9333 - precision_16: 0.8847 - recall_15: 1.0000 - val_loss: 1.8623 - val_precision_16: 0.8890 - val_recall_15: 1.0000
Epoch 3/5
78/78 [==============================] - 4s 45ms/step - loss: 1.9333 - precision_16: 0.8847 - recall_15: 1.0000 - val_loss: 1.8623 - val_precision_16: 0.8890 - val_recall_15: 1.0000
Epoch 4/5
78/78 [==============================] - 2s 30ms/step - loss: 1.9333 - precision_16: 0.8847 - recall_15: 1.0000 - val_loss: 1.8623 - val_precision_16: 0.8890 - val_recall_15: 1.0000
Epoch 5/5
78/78 [==============================] - 2s 30ms/step - loss: 1.9333 - precision_16: 0.8847 - recall_15: 1.0000 - val_loss: 1.8623 - val_precision_16: 0.8890 - val_recall_15: 1.0000

In [ ]:
len(train_y[train_y == 1])

34935

In [ ]:
len(train_y[train_y == 0])

4551